/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#include<xc.h>
#include<plib.h>

#include "OledDriver.h"
#include "OledChar.h"
#include "oledGrph.h"

#line 47 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/machine/int_types.h"
typedef unsigned char __uint8_t;
#line 49 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/machine/int_types.h"
typedef unsigned short __uint16_t;
#line 51 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/machine/int_types.h"
typedef unsigned int __uint32_t;
#line 94 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/setjmp.h"
typedef long long jmp_buf[24];
#line 95 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/setjmp.h"
typedef long long sigjmp_buf[25];
#line 137 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/sys/signal.h"
typedef unsigned long long sigset_t;
#line 128 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/sys/time.h"
struct timespec {
   long tv_sec ;
   long tv_nsec ;
};
#line 77 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/sched.h"
struct timespec;
#line 71 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/pthread/impl.h"
struct _rtpx_thread;
#line 71
struct _rtpx_thread;
#line 72 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/pthread/impl.h"
typedef struct _rtpx_thread *pthread_t;
#line 358 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/pthread.h"
struct timespec;
#line 100 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/portable/MPLAB/PIC32MX/portmacro.h"
typedef long BaseType_t;
#line 101 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/portable/MPLAB/PIC32MX/portmacro.h"
typedef unsigned long UBaseType_t;
#line 107 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/portable/MPLAB/PIC32MX/portmacro.h"
typedef __uint32_t TickType_t;
#line 103 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/task.h"
typedef void *TaskHandle_t;
#line 118 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/timers.h"
typedef void *TimerHandle_t;
#line 97 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct cbm {
   int use ;
   int data ;
   struct cbm *nextc ;
};
#line 97 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
typedef struct cbm cbm;
#line 103 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct cab_ds {
   struct cbm *free ;
   struct cbm *mrb ;
   int maxcbm ;
};
#line 115 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct fifolist {
   int data ;
   struct timespec ts ;
   struct fifolist *nextf ;
};
#line 196 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct timer_env {
   char *tname ;
   jmp_buf envn ;
};
#line 88 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/queue.h"
typedef void *QueueHandle_t;
#line 98 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/setjmp.h"
extern int setjmp(long long * ) ;
#line 136 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Demo/PIC32MX_MPLAB/FreeRTOSConfig.h"
extern void vAssertCalled(char const   *pcFileName , unsigned long ulLine ) ;
#line 360 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/task.h"
extern BaseType_t xTaskCreate(void (*pxTaskCode)(void * ) , char const   * const  pcName , __uint16_t const   usStackDepth , void * const  pvParameters , UBaseType_t uxPriority , TaskHandle_t * const  pxCreatedTask ) ;
#line 643
extern void vTaskDelete(TaskHandle_t xTaskToDelete ) ;
#line 754
extern void vTaskDelayUntil(TickType_t * const  pxPreviousWakeTime , TickType_t const   xTimeIncrement ) ;
#line 1112
extern void vTaskStartScheduler(void) ;
#line 1288
extern TickType_t xTaskGetTickCount(void) ;
#line 65 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct timespec *timepecptr  ;
#line 67 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
sigset_t sigtype  ;
#line 94 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
sigjmp_buf buf_struct  ;
#line 111 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
cbm cabmsgv  ;
#line 112 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct cab_ds cabdsv  ;
#line 121 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct fifolist fifoex  ;
#line 127
extern void ktc_fifo_init(struct fifolist *chan ) ;
#line 128
extern int ktc_fifo_read(struct fifolist **chan , int *data ) ;
#line 129
extern void ktc_fifo_write(struct fifolist **chan , int data ) ;
#line 193 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
pthread_t pthread_id_example  ;
#line 200 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
TaskHandle_t tskhndl  ;
#line 201 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
TimerHandle_t tmrhndl  ;
#line 202 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
UBaseType_t idle_prio  ;
#line 203 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
TickType_t tckvar  ;
#line 204
extern TimerHandle_t ktc_timer_init_free(struct timer_env *ptrtenv ) ;
#line 205
extern long ktc_sdelay_init_free(int intrval , char *unit , TickType_t *start_time , int id ) ;
#line 206
extern void ktc_start_time_init_free(TickType_t *start_time ) ;
#line 207
extern int ktc_fdelay_start_timer_free(int interval , char *unit , TimerHandle_t ktctimer , TickType_t start_time ) ;
#line 208
extern long ktc_fdelay_init_free(int interval , char *unit , TickType_t *start_time , TimerHandle_t ktctimer , int id ) ;
#line 209
extern struct timer_env *timer_env_array[50] ;
#line 211
/* #pragma cilnoremove("timer_env_array") */
#line 212
/* #pragma cilnoremove("taskEXIT_CRITICAL") */
#line 213
/* #pragma cilnoremove("taskENTER_CRITICAL") */
#line 214
/* #pragma cilnoremove("timer_env_array") */
#line 215
/* #pragma cilnoremove("tmrhndl") */
#line 216
/* #pragma cilnoremove("tckvar") */
#line 217
/* #pragma cilnoremove("tskhdl") */
#line 218
/* #pragma cilnoremove("idle_prio") */
#line 219
/* #pragma cilnoremove("xTaskCreate") */
#line 220
/* #pragma cilnoremove("xTaskGetTickCount") */
#line 221
/* #pragma cilnoremove("vTaskDelayUntil") */
#line 222
/* #pragma cilnoremove("vTaskDelete") */
#line 223
/* #pragma cilnoremove("ktc_start_time_init_free") */
#line 224
/* #pragma cilnoremove("ktc_timer_init_free") */
#line 225
/* #pragma cilnoremove("ktc_sdelay_init_free") */
#line 226
/* #pragma cilnoremove("setjmp") */
#line 227
/* #pragma cilnoremove("ktc_fdelay_init_free") */
#line 228
/* #pragma cilnoremove("ktc_fdelay_start_timer_free") */
#line 229
/* #pragma cilnoremove("ktc_fifo_init") */
#line 230
/* #pragma cilnoremove("ktc_fifo_read") */
#line 231
/* #pragma cilnoremove("ktc_fifo_write") */
#line 692 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/queue.h"
extern BaseType_t xQueueGenericSend(QueueHandle_t xQueue , void const   * const  pvItemToQueue , TickType_t xTicksToWait , BaseType_t const   xCopyPosition ) ;
#line 1013
extern BaseType_t xQueueGenericReceive(QueueHandle_t xQueue , void * const  pvBuffer , TickType_t xTicksToWait , BaseType_t const   xJustPeek ) ;
#line 1639
extern QueueHandle_t xQueueGenericCreate(UBaseType_t const   uxQueueLength , UBaseType_t const   uxItemSize , __uint8_t const   ucQueueType ) ;
#line 77 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Demo/Common/include/partest.h"
extern void vParTestToggleLED(UBaseType_t uxLED ) ;
#line 38 "tcarPIC32.c"
static QueueHandle_t xQueue  =    (void *)0;
#line 54
extern int ( /* missing proto */  sdelay)() ;
#line 43 "tcarPIC32.c"
// Let compile time pre-processor calculate the PR1 (period)
#define SYS_FREQ 			(80000000L)
#define PB_DIV         		8
#define PRESCALE       		1
#define TOGGLES_PER_SEC		1
#define T1_TICK       		(SYS_FREQ/PB_DIV/PRESCALE/TOGGLES_PER_SEC)
#define CPU_CT_HZ            (SYS_FREQ/2)   
#define US_TO_CT_TICKS  (CPU_CT_HZ/1000000UL)
#define CT_TICKS_TO_US  (1000000UL/CPU_CT_HZ)

void ShortDelay(                       // Short Delay 
  int DelayCount)                   // Delay Time (CoreTimer Ticks) 
{ 
  int StartTime;                    // Start Time 
  StartTime = ReadCoreTimer();         // Get CoreTimer value for StartTime 
  while ( (int)(ReadCoreTimer() - StartTime) < DelayCount ) {}; 
} 
 
int lay = 0;
void * __attribute__((__task__)) prvQueueSendTask(void *pvParameters ) 
{ 
  unsigned long ulValueToSend ;
  TimerHandle_t prvQueueSendTask_timer ;
  TickType_t start_time ;
  TickType_t temp_time ;
  struct timer_env env_prvQueueSendTask ;
  int retjmp ;

  {
  env_prvQueueSendTask.tname = "prvQueueSendTask_timer";
  ktc_start_time_init_free(& start_time);
  prvQueueSendTask_timer = ktc_timer_init_free(& env_prvQueueSendTask);
#line 44
  ulValueToSend = 100UL;
#line 46
  if (((unsigned long )pvParameters == 4369UL) == 0) {
#line 46
    vAssertCalled("tcarPIC32.c", 46);
  }
#line 51
  while (1) {
    { while (1000000< lay ){}
          OledPutString("write"); 
#line 53
    xQueueGenericSend(xQueue, & ulValueToSend, 0U, (BaseType_t )0);
    {
#line 54
    ktc_sdelay_init_free(200, "ms", & start_time, 1);
    _7: /* CIL Label */ ;
    }
    }
  }
}
}
#line 71

#line 60 "tcarPIC32.c"
void * __attribute__((__task__)) prvQueueReceiveTask(void *pvParameters ) 
{ 
  unsigned long ulReceivedValue ;
  TimerHandle_t prvQueueReceiveTask_timer ;
  TickType_t start_time ;
  TickType_t temp_time ;
  struct timer_env env_prvQueueReceiveTask ;
  int retjmp ;

  {
  env_prvQueueReceiveTask.tname = "prvQueueReceiveTask_timer";
  ktc_start_time_init_free(& start_time);
  prvQueueReceiveTask_timer = ktc_timer_init_free(& env_prvQueueReceiveTask);
#line 65
  if (((unsigned long )pvParameters == 34UL) == 0) {
#line 65
    vAssertCalled("tcarPIC32.c", 65);
  }
  {
  {
#line 67
  ktc_sdelay_init_free(100, "ms", & start_time, 2);
  _11: /* CIL Label  */
  retjmp = setjmp(env_prvQueueReceiveTask.envn);
  if (retjmp) {
    goto _16;
  }
  ktc_fdelay_start_timer_free(200, "ms", prvQueueReceiveTask_timer, start_time);
  }
#line 68
  vParTestToggleLED(1);
  }
#line 69
  while (1) {
    {
          OledPutString("read");
#line 70
    xQueueGenericReceive(xQueue, & ulReceivedValue, (TickType_t )4294967295UL, (BaseType_t )0);
    {
#line 71
    ktc_fdelay_init_free(200, "ms", & start_time, prvQueueReceiveTask_timer, 3);
    _16: /* CIL Label */ ;
    }
    }
  }
}
}
#line 75 "tcarPIC32.c"
int measureDist(void) 
{ 
  TimerHandle_t measureDist_timer ;
  TickType_t start_time ;
  TickType_t temp_time ;
  struct timer_env env_measureDist ;
  int retjmp ;
  int ov, dist;

  {
  env_measureDist.tname = "measureDist_timer";
  ktc_start_time_init_free(& start_time);
  measureDist_timer = ktc_timer_init_free(& env_measureDist);
  {
  {
#line 76
  
  _15: /* CIL Label */ ;
  }
  mPORTBClearBits(BIT_4);
  mPORTBSetBits(BIT_0);
  {
#line 77
 ShortDelay( 100 * US_TO_CT_TICKS );
  _16: /* CIL Label */ ;
  }
  { OledPutString("obst");
   mPORTBClearBits(BIT_0); 
  while(!mPORTBReadBits(BIT_4)){}  
#line 78
   int StartTime = ReadCoreTimer(); OledPutString("Put");
     while(mPORTBReadBits(BIT_4)){}   OledPutString("obst");
     ov = (ReadCoreTimer()- StartTime );
     dist = (ov * (1000000/(double)CPU_CT_HZ))/58;
    OledPutString("String");
  _17: /* CIL Label */ ;
  }
  }
#line 81
  return (dist);
}
}
  
#line 75 "tcarPIC32.c"
void * __attribute__((__task__)) prvQueueObstTask(void *pvParameters ) 
{ 
  TimerHandle_t prvQueueObstTask_timer ;
  TickType_t start_time ;
  TickType_t temp_time ;
  struct timer_env env_prvQueueObstTask ;
  int retjmp ;
  char str[40];
  int dist;

  {
  env_prvQueueObstTask.tname = "prvQueueObstTask_timer";
  ktc_start_time_init_free(& start_time);
  prvQueueObstTask_timer = ktc_timer_init_free(& env_prvQueueObstTask);
#line 80
  if (((unsigned long )pvParameters == 4369UL) == 0) {
#line 80
    vAssertCalled("tcarPIC32.c", 80);
  }
   

#line 84
  while (1) {
    {
    {  
     PORTSetPinsDigitalOut(IOPORT_B, BIT_0);
     PORTSetPinsDigitalIn(IOPORT_B, BIT_4);
     mPORTBClearBits(BIT_0);
     lay++;
     OledPutString("obst"); ktc_sdelay_init_free(200, "ms", & start_time, 1);
    
    _21: /* CIL Label */ ;
    }
    }
  }
}
}

#line 103 "tcarPIC32.c"
void main_blinky(void) 
{ 
  void *funparam ;
  TimerHandle_t main_blinky_timer ;
  TickType_t start_time ;
  TickType_t temp_time ;
  struct timer_env env_main_blinky ;
  int retjmp ;
  TaskHandle_t t_0 ;
  TaskHandle_t t_1 ;
  TaskHandle_t t_2 ; OledInit();
    OledDisplayOn();
  OledPutString("Start"); 

  
 
	SYSTEMConfig(SYS_FREQ, SYS_CFG_WAIT_STATES | SYS_CFG_PCACHE);
     
     
  {
  env_main_blinky.tname = "main_blinky_timer";
  ktc_start_time_init_free(& start_time);
  main_blinky_timer = ktc_timer_init_free(& env_main_blinky);
#line 108
  xQueue = xQueueGenericCreate(1, sizeof(unsigned long ), (__uint8_t )0U);
#line 109
  funparam = (void *)34UL;
#line 110
  idle_prio =1UL;
  xTaskCreate(prvQueueReceiveTask, "prvQueueReceiveTaskt_0", 190, funparam, idle_prio, & t_0);
#line 112
  funparam = (void *)4369UL;
#line 113
  idle_prio = 2UL;
  xTaskCreate(prvQueueSendTask, "prvQueueSendTaskt_1", 190, funparam, idle_prio, & t_1);
#line 115
  funparam = (void *)4369UL;
#line 116
  idle_prio =  3UL;
  xTaskCreate(prvQueueObstTask, "prvQueueObstTaskt_2", 190, funparam, idle_prio, & t_2);
#line 119
  vTaskStartScheduler();
  if (t_0 != (void *)0) {
    vTaskDelete(t_0);
  }
  if (t_1 != (void *)0) {
    vTaskDelete(t_1);
  }
  if (t_2 != (void *)0) {
    vTaskDelete(t_2);
  }
#line 122
  while (1) {

  }
}
}
