/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

int vTaskExitCritical(char *unit ) ;
int vTaskEnterCritical(char *unit ) ;
#line 49 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/machine/int_types.h"
typedef unsigned short __uint16_t;
#line 51 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/machine/int_types.h"
typedef unsigned int __uint32_t;
#line 94 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/setjmp.h"
typedef long long jmp_buf[24];
#line 95 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/setjmp.h"
typedef long long sigjmp_buf[25];
#line 137 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/sys/signal.h"
typedef unsigned long long sigset_t;
#line 128 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/sys/time.h"
struct timespec {
   long tv_sec ;
   long tv_nsec ;
};
#line 77 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/sched.h"
struct timespec;
#line 71 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/pthread/impl.h"
struct _rtpx_thread;
#line 71
struct _rtpx_thread;
#line 72 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/pthread/impl.h"
typedef struct _rtpx_thread *pthread_t;
#line 358 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/pthread.h"
struct timespec;
#line 100 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/portable/MPLAB/PIC32MX/portmacro.h"
typedef long BaseType_t;
#line 101 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/portable/MPLAB/PIC32MX/portmacro.h"
typedef unsigned long UBaseType_t;
#line 107 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/portable/MPLAB/PIC32MX/portmacro.h"
typedef __uint32_t TickType_t;
#line 103 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/task.h"
typedef void *TaskHandle_t;
#line 118 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/timers.h"
typedef void *TimerHandle_t;
#line 88 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/queue.h"
typedef void *QueueHandle_t;
#line 98 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct cbm {
   int use ;
   int data ;
   struct cbm *nextc ;
};
#line 98 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
typedef struct cbm cbm;
#line 104 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct cab_ds {
   struct cbm *free ;
   struct cbm *mrb ;
   int maxcbm ;
};
#line 190 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct timer_env {
   char *tname ;
   jmp_buf envn ;
};
#line 98 "/Applications/microchip/xc32/v1.42/pic32mx/include/lega-c/setjmp.h"
extern int setjmp(long long * ) ;
#line 360 "/Users/saranya/Documents/VM_Shared/ktc/bin/../FreeRTOS/Source/include/task.h"
extern BaseType_t xTaskCreate(void (*pxTaskCode)(void * ) , char const   * const  pcName , __uint16_t const   usStackDepth , void * const  pvParameters , UBaseType_t uxPriority , TaskHandle_t * const  pxCreatedTask ) ;
#line 643
extern void vTaskDelete(TaskHandle_t xTaskToDelete ) ;
#line 754
extern void vTaskDelayUntil(TickType_t * const  pxPreviousWakeTime , TickType_t const   xTimeIncrement ) ;
#line 1288
extern TickType_t xTaskGetTickCount(void) ;
#line 66 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct timespec *timepecptr  ;
#line 68 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
sigset_t sigtype  ;
#line 95 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
sigjmp_buf buf_struct  ;
#line 111 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
cbm cabmsgv  ;
#line 112 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
struct cab_ds cabdsv  ;
#line 115 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
QueueHandle_t xQueue  ;
#line 121
extern void ktc_fifo_init(QueueHandle_t *xqueue ) ;
#line 122
extern int ktc_fifo_read(QueueHandle_t *xqueue , int *data ) ;
#line 123
extern void ktc_fifo_write(QueueHandle_t *xqueue , int data ) ;
#line 187 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
pthread_t pthread_id_example  ;
#line 194 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
TaskHandle_t tskhndl  ;
#line 195 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
TimerHandle_t tmrhndl  ;
#line 196 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
#line 197 "/Users/saranya/Documents/VM_Shared/ktc/bin/../include/cilktc-free.h"
TickType_t tckvar  ;
#line 198
extern TimerHandle_t ktc_timer_init_free(struct timer_env *ptrtenv ) ;
#line 199
extern long ktc_sdelay_init_free(int intrval , char *unit , TickType_t *start_time , int id ) ;
#line 200
extern void ktc_start_time_init_free(TickType_t *start_time ) ;
#line 201
extern int ktc_fdelay_start_timer_free(int interval , char *unit , TimerHandle_t ktctimer , TickType_t start_time ) ;
#line 202
extern long ktc_fdelay_init_free(int interval , char *unit , TickType_t *start_time , TimerHandle_t ktctimer , int retjmp , int id ) ;
#line 203
extern struct timer_env *timer_env_array[50] ;
#line 205
/* #pragma cilnoremove("timer_env_array") */
#line 206
/* #pragma cilnoremove("taskYIELD") */
#line 207
/* #pragma cilnoremove("taskEXIT_CRITICAL") */
#line 208
/* #pragma cilnoremove("taskENTER_CRITICAL") */
#line 209
/* #pragma cilnoremove("timer_env_array") */
#line 210
/* #pragma cilnoremove("tmrhndl") */
#line 211
/* #pragma cilnoremove("tckvar") */
#line 212
/* #pragma cilnoremove("tskhdl") */
#line 213
/* #pragma cilnoremove("idle_prio") */
#line 214
/* #pragma cilnoremove("xTaskCreate") */
#line 215
/* #pragma cilnoremove("xTaskGetTickCount") */
#line 216
/* #pragma cilnoremove("vTaskDelayUntil") */
#line 217
/* #pragma cilnoremove("vTaskDelete") */
#line 218
/* #pragma cilnoremove("ktc_start_time_init_free") */
#line 219
/* #pragma cilnoremove("ktc_timer_init_free") */
#line 220
/* #pragma cilnoremove("ktc_sdelay_init_free") */
#line 221
/* #pragma cilnoremove("setjmp") */
#line 222
/* #pragma cilnoremove("ktc_fdelay_init_free") */
#line 223
/* #pragma cilnoremove("ktc_fdelay_start_timer_free") */
#line 224
/* #pragma cilnoremove("ktc_fifo_init") */
#line 225
/* #pragma cilnoremove("ktc_fifo_read") */
#line 226
/* #pragma cilnoremove("ktc_fifo_write") */
#line 227
/* #pragma cilnoremove("fifodt") */
#line 228
/* #pragma cilnoremove("xQueue") */
#line 6 "../rtss/fdelay.c"
extern int ( /* missing proto */  setPort)() ;
#line 7
extern int ( /* missing proto */  sdelay)() ;
#line 9
extern int ( /* missing proto */  computeA)() ;
#line 10
extern int ( /* missing proto */  fdelay)() ;
#line 11
extern int ( /* missing proto */  togglePort)() ;
#line 4 "../rtss/fdelay.c"
void motor(void) 
{ 
  int ov ;
  TimerHandle_t main_timer ;
  TickType_t start_time ;
  TickType_t temp_time ;
  struct timer_env env_main ;
  int retjmp ;
  int i;
  {
  env_main.tname = "main_timer";
  ktc_start_time_init_free(& start_time);
  main_timer = ktc_timer_init_free(& env_main);
  {
#line 6
  setPort();
  {
  _3: /* CIL Label */ ;
  {
#line 7
  ktc_sdelay_init_free(0, "ms", & start_time, 1);
  retjmp = setjmp(env_main.envn);
  if (retjmp) {
    goto _7;
  }
  ktc_fdelay_start_timer_free(100, "ms", main_timer, start_time);
  }
  }
  }
#line 8
  while (1) {
    {
#line 9
        
        computeA();
    {
    _7: /* CIL Label */ ;
    {
#line 10
    ktc_fdelay_init_free(100, "ms", & start_time, main_timer, retjmp, 2);
    retjmp = setjmp(env_main.envn);
    if (retjmp) {
      goto _7;
    }
    ktc_fdelay_start_timer_free(100, "ms", main_timer, start_time);
    }
    }
#line 11
    togglePort();
    }
  }
}
}
