/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct fifolist *fifotcChan ;
#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 133 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __pid_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 150 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef void *__timer_t;
#line 175 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
#line 98 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef __pid_t pid_t;
#line 103 "/usr/include/time.h"
typedef __timer_t timer_t;
#line 27 "/usr/include/x86_64-linux-gnu/bits/sigset.h"
struct __anonstruct___sigset_t_9 {
   unsigned long __val[1024UL / (8UL * sizeof(unsigned long ))] ;
};
#line 27 "/usr/include/x86_64-linux-gnu/bits/sigset.h"
typedef struct __anonstruct___sigset_t_9 __sigset_t;
#line 37 "/usr/include/x86_64-linux-gnu/sys/select.h"
typedef __sigset_t sigset_t;
#line 120 "/usr/include/time.h"
struct timespec {
   __time_t tv_sec ;
   __syscall_slong_t tv_nsec ;
};
#line 60 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef unsigned long pthread_t;
#line 63 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
union pthread_attr_t {
   char __size[56] ;
   long __align ;
};
#line 69 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef union pthread_attr_t pthread_attr_t;
#line 75 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
struct __pthread_internal_list {
   struct __pthread_internal_list *__prev ;
   struct __pthread_internal_list *__next ;
};
#line 75 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef struct __pthread_internal_list __pthread_list_t;
#line 90 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
struct __pthread_mutex_s {
   int __lock ;
   unsigned int __count ;
   int __owner ;
   unsigned int __nusers ;
   int __kind ;
   short __spins ;
   short __elision ;
   __pthread_list_t __list ;
};
#line 90 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
union __anonunion_pthread_mutex_t_11 {
   struct __pthread_mutex_s __data ;
   char __size[40] ;
   long __align ;
};
#line 90 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef union __anonunion_pthread_mutex_t_11 pthread_mutex_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
struct __anonstruct___data_14 {
   int __lock ;
   unsigned int __futex ;
   unsigned long long __total_seq ;
   unsigned long long __wakeup_seq ;
   unsigned long long __woken_seq ;
   void *__mutex ;
   unsigned int __nwaiters ;
   unsigned int __broadcast_seq ;
};
#line 139 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
union __anonunion_pthread_cond_t_13 {
   struct __anonstruct___data_14 __data ;
   char __size[48] ;
   long long __align ;
};
#line 139 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef union __anonunion_pthread_cond_t_13 pthread_cond_t;
#line 48 "/usr/include/stdint.h"
typedef unsigned char uint8_t;
#line 31 "/usr/include/x86_64-linux-gnu/bits/setjmp.h"
typedef long __jmp_buf[8];
#line 34 "/usr/include/setjmp.h"
struct __jmp_buf_tag {
   __jmp_buf __jmpbuf ;
   int __mask_was_saved ;
   __sigset_t __saved_mask ;
};
#line 48 "/usr/include/setjmp.h"
typedef struct __jmp_buf_tag jmp_buf[1];
#line 92 "/usr/include/setjmp.h"
typedef struct __jmp_buf_tag sigjmp_buf[1];
#line 742 "/usr/include/pthread.h"
struct __jmp_buf_tag;
#line 25 "/usr/include/asm-generic/int-ll64.h"
typedef int __s32;
#line 26 "/usr/include/asm-generic/int-ll64.h"
typedef unsigned int __u32;
#line 30 "/usr/include/asm-generic/int-ll64.h"
typedef unsigned long long __u64;
#line 41 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct threadqueue {
   pthread_mutex_t mutex ;
   pthread_cond_t cond ;
};
#line 88 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct tp_struct {
   int waiting ;
   jmp_buf env ;
   timer_t *tmr ;
};
#line 107 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct cbm {
   int use ;
   int data ;
   struct cbm *nextc ;
};
#line 107 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
typedef struct cbm cbm;
#line 113 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct cab_ds {
   struct cbm *free ;
   struct cbm *mrb ;
   int maxcbm ;
};
#line 123 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct fifolist {
   int data ;
   struct timespec ts ;
   struct fifolist *nextf ;
   pthread_mutex_t mutx ;
};
#line 130 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct sched_attr {
   __u32 size ;
   __u32 sched_policy ;
   __u64 sched_flags ;
   __s32 sched_nice ;
   __u32 __sched_priority ;
   __u64 sched_runtime ;
   __u64 sched_deadline ;
   __u64 sched_period ;
};
#line 104 "/usr/include/getopt.h"
struct option {
   char const   *name ;
   int has_arg ;
   int *flag ;
   int val ;
};
#line 6 "mist.h"
struct __anonstruct_struct_tcmist_67 {
   long aTime ;
   int rx_length ;
};
#line 6 "mist.h"
typedef struct __anonstruct_struct_tcmist_67 struct_tcmist;
#line 11 "mist.h"
struct __anonstruct_heap_t_68 {
   struct_tcmist *nodes ;
   int len ;
   int size ;
};
#line 11 "mist.h"
typedef struct __anonstruct_heap_t_68 heap_t;
#line 25 "mist.h"
struct _simulator_trxvu_rx_frame {
   unsigned short rx_length ;
   long absoluteTime ;
   uint8_t *rx_framedata ;
};
#line 25 "mist.h"
typedef struct _simulator_trxvu_rx_frame SimulatorTrxvuRxFrame;
#line 468 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) calloc)(size_t __nmemb , size_t __size )  __attribute__((__malloc__)) ;
#line 764
extern void ( __attribute__((__nonnull__(1,4))) qsort)(void *__base , size_t __nmemb , size_t __size , int (*__compar)(void const   * , void const   * ) ) ;
#line 447 "/usr/include/unistd.h"
extern unsigned int sleep(unsigned int __seconds ) ;
#line 759
extern  __attribute__((__nothrow__)) __pid_t fork(void) ;
#line 1061
extern  __attribute__((__nothrow__)) long ( __attribute__((__leaf__)) syscall)(long __sysno  , ...) ;
#line 59 "/usr/include/setjmp.h"
extern  __attribute__((__nothrow__)) int __sigsetjmp(struct __jmp_buf_tag *__env , int __savemask ) ;
#line 233 "/usr/include/pthread.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,3))) pthread_create)(pthread_t * __restrict  __newthread , pthread_attr_t const   * __restrict  __attr , void *(*__start_routine)(void * ) , void * __restrict  __arg ) ;
#line 250
extern int pthread_join(pthread_t __th , void **__thread_return ) ;
#line 22 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
int policy  =    0;
#line 23
extern int setschedvar ;
#line 37
extern int period ;
#line 38
extern int runtime ;
#line 39
extern int deadline ;
#line 79 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct timespec *timepecptr  ;
#line 80 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
timer_t ftimer  ;
#line 81 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
sigset_t sigtype  ;
#line 82
extern int ktc_critical_end(sigset_t *orig_mask ) ;
#line 83
extern int ktc_critical_start(sigset_t *orig_mask ) ;
#line 84
extern int ktc_set_sched(int policy , int runtime , int deadline , int period ) ;
#line 95 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
_Bool boolvar  ;
#line 96 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct tp_struct tp_struct_data  ;
#line 97 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
int list_pr[500]  = {      4};
#line 98 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
int list_dl[500]  = {      4};
#line 99
extern void ktc_create_timer(timer_t *ktctimer , struct tp_struct *tp , int num ) ;
#line 100
extern int ktc_start_time_init(struct timespec *start_time ) ;
#line 101
extern long ktc_sdelay_init(int deadline , int period , int unit , struct timespec *start_time , int id ) ;
#line 102
extern long ktc_gettime(int unit ) ;
#line 103
extern long ktc_fdelay_init(int interval , int period , int unit , struct timespec *start_time , int id , int num , int retjmp ) ;
#line 104 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
sigjmp_buf buf_struct  ;
#line 120 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
cbm cabmsgv  ;
#line 121 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct cab_ds cabdsv  ;
#line 148 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct sched_attr sae  ;
#line 149 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct fifolist fifoex  ;
#line 151
extern int compare_qsort(void const   *elem1 , void const   *elem2 ) ;
#line 152
int populatelist(int num ) ;
#line 153
extern struct cbm *ktc_htc_reserve(struct cab_ds *cab ) ;
#line 154
extern void ktc_htc_putmes(struct cab_ds *cab , struct cbm *buffer ) ;
#line 155
extern cbm *ktc_htc_getmes(struct cab_ds *cab ) ;
#line 156
extern void ktc_htc_unget(struct cab_ds *cab , cbm *buffer ) ;
#line 157
extern int ktc_fifo_init(struct threadqueue *queue ) ;
#line 158
extern void ktc_fifo_write(struct threadqueue *queue , void *fifolistt , int *fifocount , int *fifotail , void *data , int size ) ;
#line 159
extern void ktc_fifo_read(struct threadqueue *queue , void *fifolistt , int *fifocount , int *fifotail , void *data , int size , struct timespec *wt ) ;
#line 160
extern void ktc_simpson(int *sdata , int *tdata ) ;
#line 162 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
size_t s  ;
#line 163 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct option o  ;
#line 164 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
__inline static int sched_getattr(pid_t pid , struct sched_attr *attr , unsigned int size , unsigned int flags ) 
{ 
  int tmp ;
  int runtime ;
  int deadline ;
  int period ;
  int priority ;
  int policy ;
  char *taskid ;
  int setschedvar ;
  timer_t ktctimer ;
  struct timespec start_time ;
  struct tp_struct tp ;
  sigset_t orig_mask ;
  int retjmp ;

  {
  ktc_create_timer(& ktctimer, & tp, 1);
  {
  {
  ktc_sdelay_init(-1404, -1404, 0, & start_time, 1);
  _2: /* CIL Label */ ;
  }
  }
  taskid = "sched_getattr";
  setschedvar = 0;
#line 164
  tmp = (int )syscall(315, pid, attr, size, flags);
#line 164
  return (tmp);
}
}
#line 223
extern int ktc_fdelay_start_timer(int interval , int unit , timer_t ktctimer , struct timespec *start_time ) ;
#line 224 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
pthread_t pthread_id_example  ;
#line 251
/* #pragma cilnoremove("compare_qsort") */
#line 252
/* #pragma cilnoremove("ktc_htc_reserve") */
#line 253
/* #pragma cilnoremove("ktc_htc_putmes") */
#line 254
/* #pragma cilnoremove("ktc_htc_getmes") */
#line 255
/* #pragma cilnoremove("ktc_htc_unget") */
#line 256
/* #pragma cilnoremove("cabmsgv") */
#line 257
/* #pragma cilnoremove("cabdsv") */
#line 258
/* #pragma cilnoremove("boolvar") */
#line 259
/* #pragma cilnoremove("fork") */
#line 260
/* #pragma cilnoremove("exec_child") */
#line 261
/* #pragma cilnoremove("pthread_id_example") */
#line 262
/* #pragma cilnoremove("sigtype") */
#line 263
/* #pragma cilnoremove("next") */
#line 264
/* #pragma cilnoremove("ktc_start_time_init") */
#line 265
/* #pragma cilnoremove("ktc_sdelay_init") */
#line 266
/* #pragma cilnoremove("ktc_fdelay_init") */
#line 267
/* #pragma cilnoremove("timepecptr") */
#line 268
/* #pragma cilnoremove("env") */
#line 269
/* #pragma cilnoremove("ftimer") */
#line 270
/* #pragma cilnoremove("ktc_create_timer") */
#line 271
/* #pragma cilnoremove("tp_struct_data") */
#line 272
/* #pragma cilnoremove("__sigsetjmp") */
#line 273
/* #pragma cilnoremove("pthread_join") */
#line 274
/* #pragma cilnoremove("pthread_tryjoin_np") */
#line 275
/* #pragma cilnoremove("pthread_create") */
#line 276
/* #pragma cilnoremove("ktc_fdelay_start_timer") */
#line 277
/* #pragma cilnoremove("ktc_critical_end") */
#line 278
/* #pragma cilnoremove("ktc_critical_start") */
#line 279
/* #pragma cilnoremove("fifoex") */
#line 280
/* #pragma cilnoremove("ktc_fifo_init") */
#line 281
/* #pragma cilnoremove("ktc_fifo_read") */
#line 282
/* #pragma cilnoremove("ktc_fifo_write") */
#line 283
/* #pragma cilnoremove("ktc_simpson") */
#line 284
/* #pragma cilnoremove("ktc_set_sched") */
#line 285
/* #pragma cilnoremove("ktc_gettime") */
#line 286
/* #pragma cilnoremove("list_dl") */
#line 287
/* #pragma cilnoremove("list_pr") */
#line 288
/* #pragma cilnoremove("populatelist") */
#line 289
/* #pragma cilnoremove("sched_getattr") */
#line 290
/* #pragma cilnoremove("sae") */
#line 18 "mist.h"
extern int deviceHandle ;
#line 33
extern int simulatorTrxvu_rcGetCommandFrame(int index , SimulatorTrxvuRxFrame *rx_frame ) ;
#line 38
extern void push(heap_t *h , struct_tcmist *rxCompleteCmd ) ;
#line 39
extern void pop(heap_t *h , struct_tcmist *rxCompleteCmd ) ;
#line 40
extern struct_tcmist *top(heap_t *h ) ;
#line 41
extern void executeTCAux(struct_tcmist timedCmd ) ;
#line 42
extern int decodeTCMISTGetTime(uint8_t *packet ) ;
#line 43
extern int mistComputeADCS() ;
#line 44
extern int mistHK() ;
#line 45
extern void mistTimeInit() ;
#line 47
extern int printTrace() ;
#line 48
extern void misti2cStart() ;
#line 7 "del.c"
heap_t *prioq  ;
#line 8 "del.c"
struct_tcmist tcChanktclist[50]  ;
#line 8 "del.c"
int tcChanktccount = 0 ;
#line 8 "del.c"
int tcChanktctail  = 0;
#line 8 "del.c"
struct threadqueue  __attribute__((__fifochannel__)) tcChan  ;
#line 12
extern int ( /* missing proto */  sdelay)() ;
#line 11 "del.c"
void * __attribute__((__task__)) adcs(void) 
{ 
  int while_var ;
  int runtime ;
  int deadline ;
  int period ;
  int priority ;
  int policy ;
  char *taskid ;
  int setschedvar ;
  timer_t ktctimer ;
  struct timespec start_time ;
  struct tp_struct tp ;
  sigset_t orig_mask ;
  int retjmp ;

  {
  ktc_create_timer(& ktctimer, & tp, 2);
  {
  {
  ktc_sdelay_init(-1404, -1404, 0, & start_time, 2);
  _8: /* CIL Label */ ;
  }
  }
  taskid = "adcs";
  setschedvar = 0;
  {
#line 12
  setschedvar = 1;
#line 12
  policy = 1;
  {
  {
  {
#line 12
  ktc_sdelay_init(-2103, -2103, -3, & start_time, 3);
  _15: /* CIL Label */ ;
  }
  }
  if (setschedvar) {
    runtime = 1;
    deadline = 1;
    period = 1;
    ktc_set_sched(policy, runtime, period, deadline);
  }

  }
#line 13
  mistTimeInit();
#line 14
  while_var = 1;
  }
#line 14
  while (while_var) {
    {
#line 15
    mistComputeADCS();
    {
    {
#line 16
    ktc_sdelay_init(1, 1, 0, & start_time, 4);
    _26: /* CIL Label */ ;
    }
    }
    }
  }
#line 18
  return ((void */* __attribute__((__task__)) */)0);
}
}
#line 20 "del.c"
void * __attribute__((__task__)) collectHK(void) 
{ 
  int while_var ;
  int runtime ;
  int deadline ;
  int period ;
  int priority ;
  int policy ;
  char *taskid ;
  int setschedvar ;
  timer_t ktctimer ;
  struct timespec start_time ;
  struct tp_struct tp ;
  sigset_t orig_mask ;
  int retjmp ;

  {
  ktc_create_timer(& ktctimer, & tp, 3);
  {
  {
  ktc_sdelay_init(-1404, -1404, 0, & start_time, 5);
  _29: /* CIL Label */ ;
  }
  }
  taskid = "collectHK";
  setschedvar = 0;
  {
#line 21
  setschedvar = 1;
#line 21
  policy = 1;
  {
  {
  {
#line 21
  ktc_sdelay_init(-2103, -2103, -3, & start_time, 6);
  _36: /* CIL Label */ ;
  }
  }
  if (setschedvar) {
    runtime = 30;
    deadline = 30;
    period = 30;
    ktc_set_sched(policy, runtime, period, deadline);
  }

  }
#line 22
  while_var = 1;
  }
#line 22
  while (while_var) {
    {
#line 23
    mistHK();
    {
    {
#line 24
    ktc_sdelay_init(30, 30, 0, & start_time, 7);
    _47: /* CIL Label */ ;
    }
    }
    }
  }
#line 26
  return ((void */* __attribute__((__task__)) */)0);
}
}
#line 34
extern int ( /* missing proto */  printmistretrieve)() ;
#line 28 "del.c"
void * __attribute__((__task__)) retrieve(void) 
{ 
  unsigned char rxFrameB[200] ;
  unsigned int tmp ;
  SimulatorTrxvuRxFrame rxFrameCmd ;
  struct_tcmist tc ;
  int while_var ;
  int runtime ;
  int deadline ;
  int period ;
  int priority ;
  int policy ;
  char *taskid ;
  int setschedvar ;
  timer_t ktctimer ;
  struct timespec start_time ;
  struct tp_struct tp ;
  sigset_t orig_mask ;
  int retjmp ;

  {
  ktc_create_timer(& ktctimer, & tp, 4);
  {
  {
  ktc_sdelay_init(-1404, -1404, 0, & start_time, 8);
  _50: /* CIL Label */ ;
  }
  }
  taskid = "retrieve";
  setschedvar = 0;
#line 29
  rxFrameB[0] = 0;
#line 29
  tmp = 1U;
#line 29
  while (! (tmp >= 200U)) {
#line 29
    rxFrameB[tmp] = (unsigned char)0;
#line 29
    tmp ++;
  }
  {
#line 30
  rxFrameCmd.rx_length = 0;
#line 30
  rxFrameCmd.absoluteTime = 0;
#line 30
  rxFrameCmd.rx_framedata = rxFrameB;
#line 32
  setschedvar = 1;
#line 32
  policy = 1;
  {
  {
  {
#line 32
  ktc_sdelay_init(-2103, -2103, -3, & start_time, 9);
  _62: /* CIL Label */ ;
  }
  }
  if (setschedvar) {
    runtime = 3;
    deadline = 3;
    period = 3;
    ktc_set_sched(policy, runtime, period, deadline);
  }

  }
#line 33
  while_var = 1;
  }
#line 33
  while (while_var) {
#line 34
    printmistretrieve();
#line 35
    printTrace();
#line 36
    simulatorTrxvu_rcGetCommandFrame(deviceHandle, & rxFrameCmd);
#line 37
    if ((int )rxFrameCmd.rx_length > 0) {
#line 38
      rxFrameCmd.absoluteTime = (long )decodeTCMISTGetTime(rxFrameCmd.rx_framedata);
#line 39
      tc.aTime = rxFrameCmd.absoluteTime;
#line 40
      tc.rx_length = rxFrameCmd.rx_length;
    } else {
#line 43
      tc.aTime = 0;
#line 44
      tc.rx_length = 0;
    }
#line 46
    if (tc.rx_length != 0) {
      {
		printf("rxFrameCmd-3\n");
      ktc_fifo_write(& tcChan, & tcChanktclist, & tcChanktccount, & tcChanktctail, (unsigned long )(& tc), sizeof((tc)));
      }
    }
    {
    {
    {
#line 49
    ktc_sdelay_init(3, 3, 0, & start_time, 10);
    _79: /* CIL Label */ ;
    }
    }
    }
  }
#line 51
  return ((void */* __attribute__((__task__)) */)0);
}
}
#line 60
extern int ( /* missing proto */  printmistexecute)() ;
#line 62
extern int ( /* missing proto */  nelem)() ;
#line 53 "del.c"
void * __attribute__((__task__)) executeTC(void) 
{ 
  struct_tcmist tc ;
  struct_tcmist *tctop ;
  long t ;
  long tctime ;
  int while_var ;
  int tmp ;
  int runtime ;
  int deadline ;
  int period ;
  int priority ;
  int policy ;
  char *taskid ;
  int setschedvar ;
  timer_t ktctimer ;
  struct timespec start_time ;
  struct tp_struct tp ;
  sigset_t orig_mask ;
  int retjmp ;

  {
  ktc_create_timer(& ktctimer, & tp, 5);
  {
  {
  ktc_sdelay_init(-1404, -1404, 0, & start_time, 11);
  _82: /* CIL Label */ ;
  }
  }
  taskid = "executeTC";
  setschedvar = 0;
  {
#line 55
  tctop = (void *)0;
#line 56
  t = 0;
#line 56
  tctime = 0;
#line 57
  setschedvar = 1;
#line 57
  policy = 1;
  {
  {
#line 57
  ktc_sdelay_init(-2103, -2103, -3, & start_time, 12);
  _88: /* CIL Label */ ;
  }
  }
#line 58
  runtime = 4;
#line 58
  deadline = 4;
#line 58
  period = 4;
#line 58
  ktc_set_sched(policy, runtime, period, deadline);
#line 58
  setschedvar = 0;
#line 59
  while_var = 1;
  }
#line 59
  while (while_var) {
#line 60
    printmistexecute();
#line 61
    printTrace();
#line 62
    printf("executeTC-1\n");
    tmp = nelem(&tcChan, &tcChanktccount, &tcChanktctail);
    printf("executeTC-2\n");
#line 62
    if (tmp != 0) {
#line 62
      goto _L;
    } else
#line 62
    if (prioq->len == 0) {
      _L: /* CIL Label */ 
      {
	printf("executeTC-3\n");
      ktc_fifo_read(& tcChan, & tcChanktclist, & tcChanktccount, & tcChanktctail, (& tc), sizeof(tc), 0);
      printf("executeTC-4\n");
	}
#line 65
      push(prioq, & tc);
    }
    {
#line 67
    tctop = top(prioq);
#line 68
    tctime = tctop->aTime;
#line 69
    t = ktc_gettime(0);
    ktc_sdelay_init(-1404, -1404, 0, & start_time, 13);
    {
    {
#line 69
    printf("tctime %d %d %d %d\n",tcChanktclist[tcChanktctail].aTime, tctop->aTime, t, tctime - t);
    ktc_sdelay_init((tctime - t), (tctime - t), 0, & start_time, 13);
    _103: /* CIL Label */ ;
    }
    }
#line 71
    pop(prioq, & tc);
#line 72
    executeTCAux(tc);
    }
  }
#line 74
  return ((void */* __attribute__((__task__)) */)0);
}
}
#line 77 "del.c"
void *dummyglobalvariable  ;
#line 77 "del.c"
int populatelist(int num ) 
{ 
  int runtime ;
  int deadline ;
  int period ;
  int priority ;
  int policy ;
  char *taskid ;
  int setschedvar ;
  timer_t ktctimer ;
  struct timespec start_time ;
  struct tp_struct tp ;
  sigset_t orig_mask ;
  int retjmp ;

  {
  list_dl[1] = 1;
  list_pr[1] = 1;
  list_dl[2] = 30;
  list_pr[2] = 30;
  list_dl[3] = 3;
  list_pr[3] = 3;
  ktc_create_timer(& ktctimer, & tp, 6);
  {
  {
  ktc_sdelay_init(-1404, -1404, 0, & start_time, 14);
  _107: /* CIL Label */ ;
  }
  }
  taskid = "populatelist";
  setschedvar = 0;
#line 77
  if (num == 0) {
#line 77
    return (0);
  }
#line 77
  qsort(list_dl, num, sizeof(int ), & compare_qsort);
#line 77
  qsort(list_pr, num, sizeof(int ), & compare_qsort);
#line 77
  return (0);
}
}
#line 81
extern int ( /* missing proto */  mistinitTime)() ;
#line 87
extern int ( /* missing proto */  WDT_start)() ;
#line 77 "del.c"
void main(void) 
{ 
  int tempinitvarktc ;
  int runtime ;
  int deadline ;
  int period ;
  int priority ;
  int policy ;
  char *taskid ;
  int setschedvar ;
  timer_t ktctimer ;
  struct timespec start_time ;
  struct tp_struct tp ;
  sigset_t orig_mask ;
  int retjmp ;
  pthread_t t_0 ;
  pthread_t t_1 ;
  pthread_t t_2 ;
  pthread_t t_3 ;
  void *t_3_join ;
  void *t_2_join ;
  void *t_1_join ;
  void *t_0_join ;

  {
  populatelist(4);
  ktc_create_timer(& ktctimer, & tp, 7);
  {
  {
  ktc_sdelay_init(-1404, -1404, 0, & start_time, 15);
  _115: /* CIL Label */ ;
  }
  }
  taskid = "main";
  setschedvar = 0;
  {
  ktc_fifo_init(& tcChan);
  }
#line 80
  prioq = (heap_t *)calloc(1, sizeof(heap_t ));
#line 81
  mistinitTime();
#line 82
  misti2cStart();
  pthread_create(& t_0, 0, adcs, (void *)0);
  pthread_create(& t_1, 0, retrieve, (void *)0);
  pthread_create(& t_2, 0, executeTC, (void *)0);
  pthread_create(& t_3, 0, collectHK, (void *)0);
#line 87
  WDT_start();
  pthread_join(t_0, & t_0_join);
  pthread_join(t_1, & t_1_join);
  pthread_join(t_2, & t_2_join);
  pthread_join(t_3, & t_3_join);
#line 88
  return;
}
}
